config/routes.rb
Rails.application.routes.draw do

	root to: 'videos#index'
	resources :videos, only: [:index, :show] do
		resource :edit_title, only: [:show] do
			member do
				post :show
			end
		end
	end
	resources :users, only: [:create]
	resources :favorites, only: [:index, :show, :create, :destroy] do
		member do
			post :show
		end
	end
	resources :histories, only: [:index, :show, :create] do
		member do
			post :show
		end
	end
	resources :watch_later, only: [:index, :show, :create, :destroy] do
		member do
			post :show
		end
	end
	resources :highly_rated_videos, only: [:index, :show, :create, :destroy] do
		member do
			post :show
		end
	end
	resources :disliked_videos, only: [:update]

	resources :results, only: [:show] do
		member do
			post :show
		end
	end

	resources :tags, only: [:create, :destroy]

	get 'tags/:tag_name(/:id)' => 'tags#index', defaults: {id: 0}, constraints: {id: /\d+/}
	post 'tags/:tag_name(/:id)' => 'tags#index', defaults: {id: 0}, constraints: {id: /\d+/}

	post 'all_videos/:order(/:id)' => 'all_videos#show', defaults: {id: 0}, constraints: {order: /new|popular/, id: /\d+/}
	get 'all_videos/:order(/:id)' => 'all_videos#show', defaults: {id: 0}, constraints: {order: /new|popular/, id: /\d+/}

	resource :tag_cloud, only: [:show]

	resource :signup, only: [:show]
	resource :login,  only: [:show] do
		member do
			post :auth
		end
	end

	resource :logout, only: [:show]
	resource :about, only: [:show]
	resource :contact, only: [:show] do
		member do
			post :sendmail
		end
	end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :check_logined, only: [:index, :show]

  def index
    @LIST_NUM_INDEX = 12
    @new_video_infos = VideoInfo.all.limit(@LIST_NUM_INDEX).order(id: :desc)
    @popular_video_infos = VideoInfo.all.order(total_number_of_views: :desc).limit(@LIST_NUM_INDEX)
    render layout: 'outer'
  end

  def show
    @video_infos = VideoInfo.find_by(id: params[:id])
  	if @video_infos != nil then
  		@tag_infos = VideoTag.where(video_id: params[:id])

  		@video_infos.update(total_number_of_views: @video_infos.total_number_of_views + 1)

  		if @video_infos.video_type =~ /ThisAV/i
  			document = getHtmlDocument(@video_infos.video_id)
        begin
          @movie_addr = document.xpath('//source')[0].attribute('src').text
        rescue => e
          @movie_addr = nil
        end
  		end

  		if @usr != nil then
  			if History.isRecord(@usr.usr_name, params[:id]) == false then
  				@new_record = History.new(usr_name: @usr.usr_name, history_movie_id: params[:id])
  				@new_record.save
  				History.keepRecordNum(@usr.usr_name)
  			else
  				History.find_by(usr_name: @usr.usr_name, history_movie_id: params[:id]).update(updated_at: Time.now)
  			end
  		end

  		render layout: 'outer'
  	else
  		render text: '値が不正です。'
  	end
  end

  def bad
  	@message = ""
  	if @usr != nil then
  		if PoorlyRatedMovie.isRecord(@usr.usr_name, params[:id]) == true then
  			PoorlyRatedMovie.find_by(usr_name: @usr.usr_name, poorly_rated_movie_id: params[:id]).destroy
  			VideoInfo.setBad(params[:id], -1)
  			@message = "低評価を取り消しました"
  		else
  			@new_record = PoorlyRatedMovie.new(usr_name: @usr.usr_name, poorly_rated_movie_id: params[:id])
  			@new_record.save
  			VideoInfo.setBad(params[:id], 1)
  			@message = "この動画を低評価しました"
  		end
  	else
  		@message = "ログインしてください"
  	end
  	@bad_num = VideoInfo.getBad(params[:id])
  end

  private

  def check_logined
    if session[:usr] then
      begin
        @usr = User.find(session[:usr])
        return @usr
      rescue ActiveRecord::RecordNotFound
        reset_session
      end
    else
      @usr = nil
      return @usr
    end
  end

  def getHtmlDocument(url)
  	charset = nil
  	html = open(url, :ssl_verify_mode => OpenSSL::SSL::VERIFY_NONE) do |file|
  		charset = file.charset
  		file.read
  	end

  	if charset == 'iso-8859-1' then
  		charset = 'utf-8'
  	end

  	return Nokogiri::HTML.parse(html, nil, charset)
  end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/index.html.erb
<div id="content">
	<% @title = 'トップ' %>
	<div class="index_ad_pc">
		<!-- admax -->
		<script src="//adm.shinobi.jp/s/e4ff0c038207c5af725ddfb97895a474"></script>
		<!-- admax -->
	</div>

	<div class="index_ad_sp">
		<!-- admax -->
		<script src="//adm.shinobi.jp/s/ae5341676559a76bcbb1d6c8a27abd6e"></script>
		<!-- admax -->
	</div>

	<div class="new_movie outer_frame">
		<p>新着動画</p>
		<% @new_video_infos.each do |video_info| %>
		<article class="movie_list">
			<%= link_to url_for(controller: :videos, action: :show, id: video_info.id) do %>
				<div class="thumbnail">
					<% if video_info.thumbnail == '' then %>
						<%= image_tag "#{video_info.id}.jpg" %>
					<% else %>
						<img src="<%= video_info.thumbnail %>" alt="thumbnail">
					<% end %>
					<time><%= video_info.time.to_s.split(" ")[1] %></time>
				</div>
				<p><%= video_info.title.truncate(50, omission: "...") %></p>
			<% end %>
			<% @tags = VideoTag.where(video_id: video_info.id) %>
			<% @tags.each_with_index do |tag, index| %>
				<% break if index > 4 %>
				<% next if tag.tag == video_info.video_type %>
				<%= link_to tag.tag, url_for(controller: :tags, tag_name: tag.tag), class: "tag_list" %>
			<% end %>
			<%= link_to url_for(controller: :tags, tag_name: video_info.video_type) do %>
				<p><span class="movie_site"><%= video_info.video_type %></span></p>
			<% end %>
			<p><span class="number_of_views">視聴回数：<%= video_info.total_number_of_views %></span></p>
		</article>
		<% end %>
		<p class="right"><%= link_to 'もっと見る', url_for(controller: :all_videos, action: :show, order: :new, id: 1) %></p>
	</div>

	<div class="index_ad_pc">
		<!-- admax -->
		<script src="//adm.shinobi.jp/s/e4ff0c038207c5af725ddfb97895a474"></script>
		<!-- admax -->
	</div>

	<div class="index_ad_sp">
		<!-- admax -->
		<script src="//adm.shinobi.jp/s/ae5341676559a76bcbb1d6c8a27abd6e"></script>
		<!-- admax -->
	</div>

	<div class="popular_movie outer_frame">
		<p>人気動画</p>
		<% @popular_video_infos.each do |video_info| %>
		<article class="movie_list">
			<%= link_to url_for(controller: :videos, action: :show, id: video_info.id) do %>
			<div class="thumbnail">
				<% if video_info.thumbnail == '' then %>
					<%= image_tag "#{video_info.id}.jpg" %>
				<% else %>
					<img src="<%= video_info.thumbnail %>" alt="thumbnail">
				<% end %>
				<time><%= video_info.time.to_s.split(" ")[1] %></time>
			</div>
			<p><%= video_info.title.truncate(50, omission: "...") %></p>
			<% end %>
			<% @tags = VideoTag.where(video_id: video_info.id) %>
			<% @tags.each_with_index do |tag, index| %>
				<% break if index > 4 %>
				<% next if tag.tag == video_info.video_type %>
				<%= link_to tag.tag, url_for(controller: :tags, tag_name: tag.tag), class: "tag_list" %>
			<% end %>
			<%= link_to url_for(controller: :tags, tag_name: video_info.video_type) do %>
				<p><span class="movie_site"><%= video_info.video_type %></span></p>
			<% end %>
			<p><span class="number_of_views">視聴回数：<%= video_info.total_number_of_views %></span></p>
		</article>
		<% end %>
		<p class="right"><%= link_to 'もっと見る', url_for(controller: :all_videos, action: :show, order: :popular, id: 1) %></p>
	</div>
</div>

app/views/videos/show.html.erb
<div id="video_page_content">
	<div class="popup">
		<i class="fa fa-check" aria-hidden="true"></i>
		<p></p>
	</div>
	<div class="content_wrapper">
		<article class="movie_screen">
			<% if @video_infos.video_type == 'xvideos' %>
				<iframe src="https://flashservice.xvideos.com/embedframe/<%= @video_infos.video_id.sub(/video/, "") %>" frameborder=0 scrolling=no allowfullscreen=allowfullscreen></iframe>
			<% elsif @video_infos.video_type == 'pornhub' %>
				<iframe src="https://jp.pornhub.com/embed/<%= @video_infos.video_id %>" frameborder="0" width="560" height="340" scrolling="no" allowfullscreen></iframe>
			<% elsif @video_infos.video_type == 'erovideo' %>
				<iframe frameborder="0" scrolling="no" allowfullscreen="allowfullscreen" src="http://ero-video.net/blogframe/?mcd=<%= @video_infos.video_id %>"></iframe>
			<% elsif @video_infos.video_type =~ /TokyoTube/i %>
				<div class="tokyotube_movie">
					<script type="text/javascript" src="http://www.tokyo-tube.com/embedcode/v<%= @video_infos.video_id %>/u/player"></script>
				</div>
			<% elsif @video_infos.video_type =~ /sharemovie|share movie/i %>
				<iframe src="http://smv.to/embed/<%= @video_infos.video_id %>/" frameborder=0 width="1280" height="720" scrolling=no></iframe>
			<% elsif @video_infos.video_type =~ /ThisAV/i %>
				<% if @movie_addr != nil %>
					<video src="<%= @movie_addr %>" autoplay controls poster='<%= @video_infos.thumbnail %>'>
						<p>動画の再生にはvideoタグに対応したブラウザが必要です。</p>
					</video>
				<% else %>
					<p>動画が削除されています。</p>
				<% end %>
			<% end %>
			<div class="movie_info">
				<h2><%= @video_infos.title %></h2>
				<% @title = @video_infos.title %>
				<p class="title_edit_link"><%= link_to 'タイトルを編集', video_edit_title_path(params[:id]) %></p>
				<% if @video_infos.comment != nil %>
				<p><%= @video_infos.comment %></p>
				<% end %>
				<p class="right"><span class="total_number_of_views">視聴回数：<%= @video_infos.total_number_of_views %></span></p>

				<div class="good_and_bad">
				<%= form_tag(favorites_path, remote: true, class: :add_favorite_form) do %>
					<%= hidden_field_tag :id, params[:id] %>
					<%= button_tag type: 'submit', class: "add_favorite function_btn" do %>
					<i class="fa fa-star" aria-hidden="true"></i>
					<% end %>
				<% end %>
				<%= form_tag(watch_later_index_path, remote: true, class: :add_after_movie_form) do %>
					<%= hidden_field_tag :id, params[:id] %>
					<%= button_tag type: 'submit', class: "add_after_movie function_btn" do %>
					<i class="fa fa-bookmark" aria-hidden="true"></i>
					<% end %>
				<% end %>
				<%= form_tag({controller: :disliked_videos, action: :update, id: @video_infos.id}, remote: true, method: :patch, class: :thums_down_form) do %>
					<%= hidden_field_tag :id, params[:id] %>
					<%= button_tag type: 'submit', class: "thums_down function_btn" do %>
					<i class="fa fa-thumbs-down" aria-hidden="true"></i>
					<% end %>
					<span class="thums_down_num"><%= @video_infos.bad %></span>
				<% end %>
				<%= form_tag(highly_rated_videos_path, remote: true, class: :thums_up_form) do %>
					<%= hidden_field_tag :id, params[:id] %>
					<%= button_tag type: 'submit', class: "thums_up function_btn" do %>
					<i class="fa fa-thumbs-up" aria-hidden="true"></i>
					<% end %>
					<span class="thums_up_num"><%= @video_infos.good %></span>
				<% end %>
				</div>
			</div>

			<div class="movie_info tags">
				<p>tags：</p>
				<% if @tag_infos != nil then %>
					<% tag_index = 1; %>
					<% @tag_infos.each do |tag_info| %>
						<%= link_to url_for(controller: :tags, tag_name: tag_info.tag) do %>
							<span class="<%= tag_info.tag %>"><%= tag_info.tag %></span>
						<% end %>
						<% if tag_index != 1 then %>
							<%= form_tag(tag_path, class: "tag_delete_form tag_delete_form_" + tag_info.tag, remote: true, method: :delete) do %>
								<%= hidden_field_tag :tag_name, tag_info.tag %>
								<%= hidden_field_tag :deleted_tag, tag_info.tag %>
								<%= hidden_field_tag :tag_current_size, @tag_infos.length, class: "tag_current_size" %>
								<%= button_tag type: 'submit', class: "tag_delete_btn" do %>
									<i class="fa fa-times" aria-hidden="true"></i>
								<% end %>
							<% end %>
						<% end %>
						<% tag_index += 1 %>
					<% end %>
				<% else %>
					<% tag_index = 1 %>
				<% end %>
				<p class="right tag_edit_link">タグを編集</p>
				<%= form_tag(tags_path, class: "tag_edit_form", remote: true ) do %>
					<div class="form-group">
						<%= hidden_field_tag :id, params[:id], class: "video_id" %>
						<%= hidden_field_tag :tag_index, tag_index, class: "tag_index" %>
						<%= text_field_tag :added_tag, "", size: 50, class: "input_added_tag form-control" %>
					</div>
					<%= submit_tag '追加', class: "add_tag_btn btn btn-primary" %>
				<% end %>
			</div>
		</article>

		<aside class="relation_movie">
			<p>関連動画</p>
			<div class="relation_movie_info">
				<ul>
					<div class="video_page_ad">
						<!-- admax -->
						<script src="//adm.shinobi.jp/s/8f477c9f3b54f4d48297e7f8cf4ad1da"></script>
						<!-- admax -->
					</div>
					<% relation_video_id_list = Array.new %>
					<% offset = 0 %>
					<% @tag_infos.each do |tag_info| %>
						<% begin %>
							<% relation_video_id = VideoTag.where.not(video_id: tag_info.video_id).offset(offset).find_by(tag: tag_info.tag) %>
							<% if relation_video_id == nil then %>
								<% break %>
							<% end %>
							<% offset += 1 %>
						<% end while relation_video_id_list.include?(relation_video_id.video_id) %>
						<% if relation_video_id == nil then %>
							<% next %>
						<% end %>
						<% offset = 0 %>
						<% relation_video_id_list << relation_video_id.video_id %>
						<% video_info = VideoInfo.find_by(id: relation_video_id.video_id) %>
						<li>
							<%= link_to url_for(controller: :videos, action: :show, id: video_info.id) do %>
							<% if video_info.thumbnail == '' then %>
								<%= image_tag "#{video_info.id}.jpg" %>
							<% else %>
								<img src="<%= video_info.thumbnail %>" alt="thumbnail">
							<% end %>
							<div class="relation_movie_info_text">
								<h3><%= video_info.title.truncate(50, omission: "...") %></h3>
								<p class="right">視聴回数：<%= video_info.total_number_of_views %></p>
							</div>
							<% end %>
						</li>
					<% end %>
					<% if relation_video_id_list.length != 0 && relation_video_id_list.length < 2 then %>
						<% offset = 1 %>
						<% begin %>
							<% relation_video_id = VideoTag.where.not(video_id: @tag_infos[0].video_id).offset(offset).find_by(tag: @tag_infos[0].tag) %>
							<% if relation_video_id == nil then %>
								<% break %>
							<% end %>
							<% video_info = VideoInfo.find_by(id: relation_video_id.video_id) %>
							<li>
								<%= link_to url_for(controller: :videos, action: :show, id: video_info.id) do %>
								<% if video_info.thumbnail == '' then %>
									<%= image_tag "#{video_info.id}.jpg" %>
								<% else %>
									<img src="<%= video_info.thumbnail %>" alt="thumbnail">
								<% end %>
								<div class="relation_movie_info_text">
									<h3><%= video_info.title.truncate(50, omission: "...") %></h3>
									<p class="right">視聴回数：<%= video_info.total_number_of_views %></p>
								</div>
								<% end %>
							</li>
							<% offset += 1 %>
						<% end while relation_video_id_list.include?(relation_video_id.video_id) || offset < 4 %>
					<% end %>
				</ul>
			</div>
		</aside>
	</div>
</div>