config/routes.rb
Rails.application.routes.draw do

	root to: 'videos#index'
	resources :videos, only: [:index, :show] do
		resource :edit_title, only: [:show] do
			member do
				post :show
			end
		end
	end
	resources :users, only: [:create]
	resources :favorites, only: [:index, :show, :create, :destroy] do
		member do
			post :show
		end
	end
	resources :histories, only: [:index, :show, :create] do
		member do
			post :show
		end
	end
	resources :watch_later, only: [:index, :show, :create, :destroy] do
		member do
			post :show
		end
	end
	resources :highly_rated_videos, only: [:index, :show, :create, :destroy] do
		member do
			post :show
		end
	end
	resources :disliked_videos, only: [:update]

	resources :results, only: [:show] do
		member do
			post :show
		end
	end

	resources :tags, only: [:create, :destroy]

	get 'tags/:tag_name(/:id)' => 'tags#index', defaults: {id: 0}, constraints: {id: /\d+/}
	post 'tags/:tag_name(/:id)' => 'tags#index', defaults: {id: 0}, constraints: {id: /\d+/}

	post 'all_videos/:order(/:id)' => 'all_videos#show', defaults: {id: 0}, constraints: {order: /new|popular/, id: /\d+/}
	get 'all_videos/:order(/:id)' => 'all_videos#show', defaults: {id: 0}, constraints: {order: /new|popular/, id: /\d+/}

	resource :tag_cloud, only: [:show]

	resource :signup, only: [:show]
	resource :login,  only: [:show] do
		member do
			post :auth
		end
	end

	resource :logout, only: [:show]
	resource :about, only: [:show]
	resource :contact, only: [:show] do
		member do
			post :sendmail
		end
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :check_logined, only: [:index]

  def initialize
  	@LIST_NUM_TAG = 12
  end

  def index
    @page_num = params[:jump_page_num].nil? ? params[:id].to_i : params[:jump_page_num].to_i - 1
  	case params[:max_range]
  	when nil
  		#何もしない
  	else
  		if @page_num < 0 then
  			@page_num = 0
  		elsif @page_num > params[:max_range].to_i - 1
  			@page_num = params[:max_range].to_i - 1
  		end
  	end

    @search_query = ""

    #クエリの生成
    @sortingOption = params[:sortingOption].nil? ? 'update_day' : params[:sortingOption]
    @videoType = params[:videoType].nil? ? 'all' : params[:videoType]
    @uploadPeriod = params[:uploadPeriod].nil? ? 'all' : params[:uploadPeriod]
    @inputMovieLengthMin = params[:inputMovieLengthMin].nil? ? 'all' : params[:inputMovieLengthMin]
    @inputMovieLengthMax = params[:inputMovieLengthMax].nil? ? 'all' : params[:inputMovieLengthMax]

    case @sortingOption
    when 'update_day'
      order_option = 'id desc'
    when 'number_of_views'
      order_option = 'total_number_of_views desc'
    when 'movie_rate'
      order_option = 'good desc'
    end

    case @videoType
    when 'xvideos'
      @search_query << " and video_type = 'xvideos'"
    when 'pornhub'
      @search_query << " and (video_type = 'pornhub' or video_type = 'PornHub')"
    when 'tokyotube'
      @search_query << " and video_type = 'tokyotube'"
    when 'erovideo'
      @search_query << " and video_type = 'erovideo'"
    when 'sharemovie'
      @search_query << " and (video_type = 'sharemovie' or video_type = 'SHARE MOVIE')"
    when 'ThisAV'
      @search_query << " and video_type = 'ThisAV'"
    end

    today = Date.today
    case @uploadPeriod
    when 'today'
      @search_query << " and created_at > '#{today}'"
    when 'week'
      prev_week = today - 7
      @search_query << " and created_at > '#{Date.new(prev_week.year, prev_week.month, prev_week.day)}'"
    when 'month'
      prev_month = today << 1
      @search_query << " and created_at > '#{Date.new(prev_month.year, prev_month.month, prev_month.day)}'"
    when 'year'
      prev_year = today.year - 1
      @search_query << " and created_at > '#{Date.new(prev_year, today.month, today.day)}'"
    end

    begin
      min = Integer(@inputMovieLengthMin)
      max = Integer(@inputMovieLengthMax)

      hourMin = min / 60
      minuteMin = min % 60

      hourMax = max / 60
      minuteMax = max % 60

      minTime = Time.local(2001, 1, 1, hourMin, minuteMin, 0)
      maxTime = Time.local(2001, 1, 1, hourMax, minuteMax, 0)

      @search_query << " and time > '#{minTime.strftime('%H:%M:%S')}' and time < '#{maxTime.strftime('%H:%M:%S')}'"

    rescue ArgumentError => e
      #何もしない
    end

    @video_infos = VideoInfo.where("id in (select video_id from video_tags where tag = '#{params[:tag_name]}') #{@search_query} ").limit(@LIST_NUM_TAG).offset(@LIST_NUM_TAG * @page_num).order(order_option)
    @total_of_results = VideoInfo.where("id in (select video_id from video_tags where tag = '#{params[:tag_name]}') #{@search_query} ").count
    @pagenation_num = (@total_of_results / (@LIST_NUM_TAG * 1.0)).ceil
  	render layout: 'outer'
  end

  def create
		@message = ""
		@record_limit = 15
		@tag_info = nil
		if VideoTag.isRecord(params[:id], params[:added_tag]) == false then
			if VideoTag.isReachToLimit(params[:id], @record_limit) == false then
				@tag_info = VideoTag.new(video_id: params[:id], tag: params[:added_tag])
				@tag_info.save
				@message = "タグを追加しました。"
			else
				@message = "タグ数が上限に達しています。他のタグを削除してください。"
			end
		else
			@message = "既に登録済みのタグです。"
		end
  end

  def destroy
    referer_check = request.headers['Referer'].split('/')[4] == params[:id]
    case referer_check
    when true
      if VideoTag.isRecord(params[:id], params[:deleted_tag]) then
        VideoTag.find_by(video_id: params[:id], tag: params[:deleted_tag]).destroy
      end
    end
  end

  private

  def check_logined
    if session[:usr] then
      begin
        @usr = User.find(session[:usr])
        return @usr
      rescue ActiveRecord::RecordNotFound
        reset_session
      end
    else
      @usr = nil
      return @usr
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/create.js.erb
//alert("<%= params[:tag_index] %>");
<% if @record_limit >= eval("#{params[:tag_index]}") then %>
  <% if @tag_info != nil then %>
    $('.tag_index').attr('value', '<%= params[:tag_index].to_i + 1 %>');
    $('.tag_current_size').attr('value', '<%= params[:tag_index].to_i %>')
    $('.tag_edit_link').before($('<%= link_to url_for(controller: :tags, tag_name: @tag_info.tag) do %>\
                                    <span class="<%= @tag_info.tag %>"><%= params[:added_tag] %></span>\
                                    <% end %>\
                                    <%= form_tag({controller: :tags, action: :destroy, id: params[:id]}, class: "tag_delete_form tag_delete_form_" + @tag_info.tag, remote: true, method: :delete) do %>\
                                      <%= hidden_field_tag :tag_name, @tag_info.tag %>\
                                      <%= hidden_field_tag :deleted_tag, @tag_info.tag %>\
                                      <%= hidden_field_tag :tag_current_size, params[:tag_index], class: "tag_current_size" %>\
                                      <%= button_tag type: "submit", class: "tag_delete_btn" do %>\
                                        <i class="fa fa-times" aria-hidden="true"></i>\
                                      <% end %>\
                                    <% end %>'));
  <% end %>
<% end %>

$('.tag_delete_form').css("display", "inline-block");

var $popup = $('.popup');
var top_offset = $('.add_tag_btn').offset().top;
var left_offset = $('.add_tag_btn').offset().left;

$popup.css({
  top: top_offset + 30,
  left: left_offset
});

$('.popup p').html(
  '<%= escape_javascript("#{@message}") %>'
);

$('.popup p').css("display", "inline-block")
$popup.fadeIn('slow');

setTimeout(function() {
  $popup.fadeOut('slow');
}, 3000);

app/views/tags/destroy.js.erb
$('.tag_index').attr('value', '<%= params[:tag_current_size].to_i %>');
$('.tag_current_size').attr('value', '<%= params[:tag_current_size].to_i - 1 %>')
$('.tag_delete_form_<%= params[:tag_name] %>').remove();
$('.<%= params[:tag_name] %>').css("display", "none");

app/views/tags/index.html.erb
<div id="tag_content">
	<% @title = "タグ検索:#{params[:tag_name]}" %>
	<div class="index_ad_pc">
		<!-- admax -->
		<script src="//adm.shinobi.jp/s/e4ff0c038207c5af725ddfb97895a474"></script>
		<!-- admax -->
	</div>

	<div class="index_ad_sp">
		<!-- admax -->
		<script src="//adm.shinobi.jp/s/ae5341676559a76bcbb1d6c8a27abd6e"></script>
		<!-- admax -->
	</div>

	<div class="search_filter">
		<h2>検索フィルタ</h2>
			<%= form_tag({controller: :tags, tag_name: params[:tag_name]}, class: "search_filter_form") do %>
				<div class="form-group">
					<%= label_tag 'inputSorting', '並び替え', class: "search_filter_label" %>
					<%= select_tag 'sortingOption', options_for_select({'アップロード日' => 'update_day', '視聴回数' => 'number_of_views', '評価' => 'movie_rate'}), class: "select_box" %>
				</div>
				<div class="form-group">
					<%= label_tag 'inputVideoType', '動画サイト', class: "search_filter_label" %>
					<%= select_tag 'videoType', options_for_select({'全て' => 'all', 'erovideo' => 'erovideo', 'SHARE MOVIE' => 'sharemovie', 'ThisAV' => 'ThisAV'}), class: "select_box" %>
				</div>
				<div class="form-group">
					<%= label_tag 'inputUploadPeriod', 'アップロード日', class: "search_filter_label" %>
					<%= select_tag 'uploadPeriod', options_for_select({'全期間' => 'all', '今日' => 'today', '今週' => 'week', '今月' => 'month', '今年' => 'year'}), class: "select_box" %>
				</div>
				<div class="form-group">
					<%= label_tag 'inputMovieLength', '再生時間', class: "search_filter_label" %>
					<div class="input_movie_length_field">
						<%= text_field_tag :inputMovieLengthMin, "", class: "inputMovieLengthMin", pattern: "[0-9]*" %><span>分～</span><%= text_field_tag :inputMovieLengthMax, "", class: "inputMovieLengthMin", pattern: "[0-9]*" %><span>分までの間</span>
					</div>
				</div>
				<div class="form-group">
					<%= hidden_field_tag :keywd, params[:keywd] %>
					<%= hidden_field_tag :list_num, params[:list_num] %>
					<%= button_tag '適用', type: 'submit', class: 'search_filter_apply_btn' %>
					<%= button_tag 'キャンセル', type: 'button', class: 'search_filter_cancel_btn' %>
				</div>
			<% end %>
	</div>

	<div class="tag_movie outer_frame">
		<p>tag：<%= params[:tag_name] %> (<%= @total_of_results %>件)</p>
		<%= button_tag 'フィルタ', type: 'button', class: "search_filter_btn" %>
		<% @i = 1 %>
		<% @video_infos.each do |video_info| %>
			<article class="movie_list movie_id_<%= @i %>">
				<%= link_to url_for(controller: :videos, action: :show, id: video_info.id) do %>
				<div class="thumbnail">
					<% if video_info.thumbnail == '' then %>
						<%= image_tag "#{video_info.id}.jpg" %>
					<% else %>
						<img src="<%= video_info.thumbnail %>" alt="thumbnail">
					<% end %>
					<time><%= video_info.time.to_s.split(" ")[1] %></time>
				</div>
					<p><%= video_info.title.truncate(60, omission: "...") %></p>
				<% end %>
				<% @tags = VideoTag.where(video_id: video_info.id) %>
				<% @tags.each_with_index do |tag, index| %>
					<% break if index > 4 %>
					<% next if tag.tag == video_info.video_type %>
					<%= link_to tag.tag, url_for(controller: :tags, tag_name: tag.tag), class: "tag_list" %>
				<% end %>
				<%= link_to url_for(controller: :tags, tag_name: video_info.video_type) do %>
					<p><span class="movie_site"><%= video_info.video_type %></span></p>
				<% end %>
				<p><span class="number_of_views">視聴回数：<%= video_info.total_number_of_views %></span></p>
			</article>
			<% @i += 1 %>
		<% end %>
	</div>

	<% @controller = "tags" %>
	<% @action = "index" %>
	<% @argument_num = 7 %>
	<% @param_key_1 = "keywd" %>
	<% @param_1 = "#{params[:keywd]}" %>
	<% @param_key_2 = "list_num" %>
	<% @param_2 = "#{params[:list_num]}" %>
	<% @param_key_3 = "sortingOption" %>
	<% @param_3 = @sortingOption %>
	<% @param_key_4 = "videoType" %>
	<% @param_4 = @videoType %>
	<% @param_key_5 = "uploadPeriod" %>
	<% @param_5 = @uploadPeriod %>
	<% @param_key_6 = "inputMovieLengthMin" %>
	<% @param_6 = @inputMovieLengthMin %>
	<% @param_key_7 = "inputMovieLengthMax" %>
	<% @param_7 = @inputMovieLengthMax %>
	<%= render 'application/pagenation' %>

	<div class="index_ad_pc">
		<!-- admax -->
		<script src="//adm.shinobi.jp/s/e4ff0c038207c5af725ddfb97895a474"></script>
		<!-- admax -->
	</div>

	<div class="index_ad_sp">
		<!-- admax -->
		<script src="//adm.shinobi.jp/s/ae5341676559a76bcbb1d6c8a27abd6e"></script>
		<!-- admax -->
	</div>

</div>

app/views/tags/show.html.erb
<div id="tag_content">
	<% @title = "タグ検索:#{params[:tag_name]}" %>
	<div class="index_ad_pc">
		<!-- admax -->
		<script src="//adm.shinobi.jp/s/e4ff0c038207c5af725ddfb97895a474"></script>
		<!-- admax -->
	</div>

	<div class="index_ad_sp">
		<!-- admax -->
		<script src="//adm.shinobi.jp/s/ae5341676559a76bcbb1d6c8a27abd6e"></script>
		<!-- admax -->
	</div>

	<div class="search_filter">
		<h2>検索フィルタ</h2>
			<%= form_tag(result_path(0), class: "search_filter_form") do %>
				<div class="form-group">
					<%= label_tag 'inputSorting', '並び替え', class: "search_filter_label" %>
					<%= select_tag 'sortingOption', options_for_select({'アップロード日' => 'update_day', '視聴回数' => 'number_of_views', '評価' => 'movie_rate'}), class: "select_box" %>
				</div>
				<div class="form-group">
					<%= label_tag 'inputVideoType', '動画サイト', class: "search_filter_label" %>
					<%= select_tag 'videoType', options_for_select({'全て' => 'all', 'erovideo' => 'erovideo', 'SHARE MOVIE' => 'sharemovie', 'ThisAV' => 'ThisAV'}), class: "select_box" %>
				</div>
				<div class="form-group">
					<%= label_tag 'inputUploadPeriod', 'アップロード日', class: "search_filter_label" %>
					<%= select_tag 'uploadPeriod', options_for_select({'全期間' => 'all', '今日' => 'today', '今週' => 'week', '今月' => 'month', '今年' => 'year'}), class: "select_box" %>
				</div>
				<div class="form-group">
					<%= label_tag 'inputMovieLength', '再生時間', class: "search_filter_label" %>
					<div class="input_movie_length_field">
						<%= text_field_tag :inputMovieLengthMin, "", class: "inputMovieLengthMin", pattern: "[0-9]*" %><span>分～</span><%= text_field_tag :inputMovieLengthMax, "", class: "inputMovieLengthMin", pattern: "[0-9]*" %><span>分までの間</span>
					</div>
				</div>
				<div class="form-group">
					<%= hidden_field_tag :keywd, params[:keywd] %>
					<%= hidden_field_tag :list_num, params[:list_num] %>
					<%= button_tag '適用', type: 'submit', class: 'search_filter_apply_btn' %>
					<%= button_tag 'キャンセル', type: 'button', class: 'search_filter_cancel_btn' %>
				</div>
			<% end %>
	</div>

	<div class="tag_movie outer_frame">
		<p>tag：<%= params[:tag_name] %> (<%= @total_of_results %>件)</p>
		<%= button_tag 'フィルタ', type: 'button', class: "search_filter_btn" %>
		<% @i = 1 %>
		<% @tag_infos.each do |tag_info| %>
			<% 	@video_info = VideoInfo.find_by(id: tag_info.video_id) %>
			<article class="movie_list movie_id_<%= @i %>">
				<%= link_to url_for(controller: :videos, action: :show, id: tag_info.video_id) do %>
				<div class="thumbnail">
					<% if @video_info.thumbnail == '' then %>
						<%= image_tag "#{@video_info.id}.jpg" %>
					<% else %>
						<img src="<%= @video_info.thumbnail %>" alt="thumbnail">
					<% end %>
					<time><%= @video_info.time.to_s.split(" ")[1] %></time>
				</div>
					<p><%= @video_info.title.truncate(60, omission: "...") %></p>
				<% end %>
				<% @tags = VideoTag.where(video_id: @video_info.id) %>
				<% @tags.each_with_index do |tag, index| %>
					<% break if index > 4 %>
					<% next if tag.tag == @video_info.video_type %>
					<%= link_to tag.tag, url_for(controller: :tags, tag_name: tag.tag), class: "tag_list" %>
				<% end %>
				<%= link_to url_for(controller: :tags, tag_name: @video_info.video_type) do %>
					<p><span class="movie_site"><%= @video_info.video_type %></span></p>
				<% end %>
				<p><span class="number_of_views">視聴回数：<%= @video_info.total_number_of_views %></span></p>
			</article>
			<% @i += 1 %>
		<% end %>
	</div>

	<% @controller = "tags" %>
	<% @action = "index" %>
	<% @argument_num = 7 %>
	<% @param_key_1 = "keywd" %>
	<% @param_1 = "#{params[:keywd]}" %>
	<% @param_key_2 = "list_num" %>
	<% @param_2 = "#{params[:list_num]}" %>
	<% @param_key_3 = "sortingOption" %>
	<% @param_3 = @sortingOption %>
	<% @param_key_4 = "videoType" %>
	<% @param_4 = @videoType %>
	<% @param_key_5 = "uploadPeriod" %>
	<% @param_5 = @uploadPeriod %>
	<% @param_key_6 = "inputMovieLengthMin" %>
	<% @param_6 = @inputMovieLengthMin %>
	<% @param_key_7 = "inputMovieLengthMax" %>
	<% @param_7 = @inputMovieLengthMax %>
	<%= render 'application/pagenation' %>

	<div class="index_ad_pc">
		<!-- admax -->
		<script src="//adm.shinobi.jp/s/e4ff0c038207c5af725ddfb97895a474"></script>
		<!-- admax -->
	</div>

	<div class="index_ad_sp">
		<!-- admax -->
		<script src="//adm.shinobi.jp/s/ae5341676559a76bcbb1d6c8a27abd6e"></script>
		<!-- admax -->
	</div>

</div>